### ISSUE TITLE
Practica 6 de Reconocimiento de Imágenes_Edwin, Ivan, Alexis, Taoli

### ISSUE THREAD

**Issue by Edwin-1012** [SistemasTecTlaxiaco/reconocimiento-de-imagenes-con-ra-equipo-cafe-hue#2]
[Practica 6 de Reconocimiento de Imágenes_Edwin, Ivan, Alexis, Taoli.pdf](https://github.com/SistemasTecTlaxiaco/reconocimiento-de-imagenes-con-ra-equipo-cafe-hue/files/8617888/Practica.6.de.Reconocimiento.de.Imagenes_Edwin.Ivan.Alexis.Taoli.pdf)

**Comment by claudiasilvavenda** [comment]
La calif. 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
